FROM quay.io/np22-jpg/fedora-npm AS base

WORKDIR /usr/src/app
COPY package.json ./
RUN yarn install --production
COPY . .

FROM quay.io/np22-jpg/fedora-node AS release
USER node
COPY --from=base /usr/src/app/ /app
WORKDIR /app

HEALTHCHECK --interval=5s --timeout=3s --start-period=5s \
  CMD curl -f http://localhost:8080

EXPOSE 8080

ENTRYPOINT ["node", "server.js"]